---
title: "nonprepaydata"
output: html_document
---


# 0. 准备
```{r}
# library(data.table)
library(plyr)
library(VvMT)
library(fBasics)
library(gridExtra)
library(ggplot2)
library(rpart)
library(gbm)
library(ROCR)
library(pROC)
library(dplyr)
memory.limit(size = 50000)
```

# 1. 衍生变量生成
```{r}

```


# 2. 未购买人群分析
```{r}
nonprepaydata_varstat = VarStat(nonprepaydata, VarType(nonprepaydata), nstat = c("Miss", "Mean", "Min", "Max", "Median", "Num"))
nonprepaydata = VarDel(nonprepaydata, nonprepaydata_varstat$num_var_value$Var[nonprepaydata_varstat$num_var_value$Num == 1])
colnames(nonprepaydata)
nonprepaydata_iv = CatVarImp(nonprepaydata[, c(3:127, 130)], yvar = 'add_target', method = 'iv', bins = 10)
for (x in colnames(nonprepaydata)[c(3:127)]) {
  CShipPlot(nonprepaydata, xvar = x, yvar = 'add_target', bins = 10, pdf = T, savedir = 'D:/play/tap4fun/tap4fun/xxw_testdata/plot/nonprepay/') 
}

nonprepaydata.numericvars.index = which(VarType(nonprepaydata)$numeric)
nonprepaydata_iv; write.csv(nonprepaydata_iv[[2]], 'D:/play/tap4fun/tap4fun/xxw_testdata/plot/nonprepay/nonprepaydata_iv.csv', row.names = F)
nonprepaydata_cor = data.frame(round(cor(nonprepaydata[, nonprepaydata.numericvars.index]),2)); write.csv(nonprepaydata_cor, 'D:/play/tap4fun/tap4fun/xxw_testdata/plot/nonprepay/nonprepaydata_cor.csv', row.names = T)
```













# 4. 预测结果输出
```{r}
subdata = predictdata[, c('user_id', 'pay_price')]
colnames(subdata) = c('user_id', 'prediction_pay_price')
write.csv(subdata, 'D:/play/tap4fun/result/subdata.csv', row.names = F, quote = F)
```
